sourcedir <- "C:/Users/ucg8nb/R Projects/R_Sandbox/R_Code"
  
library(forecast)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(lattice)
library(psych)
library(dplyr)
library(mtsdi)
library(tidyverse)
library(ggfortify)
library(ggpubr)
library(tseries)
library("car")
library(here)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggfortify)
library(MASS)
library(lindia)
library(olsrr)
library(data.table)
library(plyr)
library(scales)
library(grid)
library(psych)
library(lattice)
library(car)
library(ggplot2)
library(ggpubr)
library(ggfortify)
library(ggResidpanel)
setwd(sourcedir)
source('AccidentInput.R')
source('PCAplots.R')
source("pc.glm.R")
source("ROC.R")
source("TestSet.R")

collegeData <- read.table("C:/Users/ucg8nb/Downloads/college_data.csv", header = T, sep = ',')

smallTest <- lm(Reputation ~ SAT.Verb + Size, data = collegeData)
summary(smallTest)
fullRank <- lm(Reputation ~ `Accept.Rate` + `SAT.Verb` + `SAT.Math` + `Fac.Stud` + `X..Male`, data = collegeData)
summary(fullRank)
steppedRank <- step(fullRank)
summary(steppedRank)
autoplot(steppedRank)
